# Generated by Django 3.2.3 on 2021-06-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookshop',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('book_slug', models.SlugField(max_length=200, unique=True)),
                ('book_name', models.CharField(max_length=100)),
                ('book_des', models.TextField(max_length=255)),
                ('book_img', models.FileField(blank=True, upload_to='')),
                ('book_price', models.FloatField(default=0)),
                ('book_datetime', models.DateTimeField(auto_now=True)),
                ('book_created', models.DateTimeField(auto_now_add=True)),
                ('book_recommend', models.BooleanField(default=True)),
                ('book_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=20)),
                ('category_img', models.FileField(default=None, upload_to='images/category')),
                ('categoty_activate', models.BooleanField(default=True)),
                ('category_detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/product')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.bookshop')),
            ],
        ),
        migrations.AddField(
            model_name='bookshop',
            name='book_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.category'),
        ),
    ]
