# Generated by Django 3.2.3 on 2021-06-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_alter_imageprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='name',
            field=models.ForeignKey(blank=True, default='../static/img/favicon/favicon.png', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
