# Generated by Django 3.2.3 on 2021-06-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20210618_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProfile',
        ),
    ]
